version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    restart: on-failure
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=ADMIN
      - MINIO_ROOT_PASSWORD=ADMIN@123
  storage:
    image: ghcr.io/pnstack/nestjs-storage-service:release
    container_name: nestjs-storage-service
    depends_on:
      - minio
    restart: on-failure
    ports:
      - 4006:4000
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env  
volumes:
  minio-data:
