# .github/workflows/docker-build.yml
name: Docker Build

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker:
    uses: pnstack/actions/docker-publish@main
    with:
      platforms: linux/amd64,linux/arm64
      # Optional customizations:
      dockerfile: ./Dockerfile
      context: .
      push_enabled: true
      registry: ghcr.io